### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pyhoneybot/honeybot#101]
Volunteer here

Conditions:

If you are new to Python: Send PRs to put the project in shape and you get the keys

 If you are already an experienced Python programmer (to volunteer): Send in your names here directly 

If you are already an experienced Python programmer (not volunteer): Comment here, fork and send in some PRs that will put the project back in shape!

**Comment by Iemane291** [comment]
i'm not looking forward to volunteering or maintaining honeybot but i am an experienced python programmer.

**Comment by Abdur-rahmaanJ** [comment]
@Iemane291, 1000s of excuses, but i clarified the issue above. PRs of any kind welcome though!

**Comment by Iemane291** [comment]
alright, i'll have a look into the project and make a PR if i can. (i'm not looking forward to volunteering or maintaing honeybot.)

**Comment by Abdur-rahmaanJ** [comment]
Thanks a lot! It will help future people!

**Comment by Iemane291** [comment]
don't think I can make a PR, thought this was a discord bot lmao.

**Comment by Abdur-rahmaanJ** [comment]
Np XD

**Comment by data2kinyungu** [comment]
I would volunteer as I am beginning in Open Source.

**Comment by Abdur-rahmaanJ** [comment]
@data2kinyungu Please join [our discord](https://discord.gg/E6zD4XT), we'll guide you!

**Comment by data2kinyungu** [comment]
Thank you for the invitation. Apologies for the late reply, I was offline.
I have joined the Discord server.

**Comment by oluwoleilesanmi** [comment]
Hi @Abdur-rahmaanJ I want to volunteer
