### ISSUE TITLE
make mail plugin use configparser

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pyhoneybot/honeybot#12]
you have to 

- make this plugin https://github.com/pyhoneybot/honeybot/blob/master/honeybot/plugins/mail.py use configparser 
- modify email.cfg from port:587 to port=587

**Comment by sridk** [comment]
Hey, Can I work on this?

**Comment by Abdur-rahmaanJ** [comment]
### @sridk yes!

**Comment by sridk** [comment]
Hi!
I have made changes to mail.py to use configparser. How do I test it now?

**Comment by Abdur-rahmaanJ** [comment]
no need to test for now. just pr

**Comment by sridk** [comment]
okay. I will pr in some time

**Comment by sridk** [comment]
For your reference: I have created a pr #18
