### ISSUE TITLE
Create top-level `assets` dir and move logo

### ISSUE THREAD

**Issue by MrTanoshii** [pyhoneybot/honeybot#128]
## Goals

- [ ] Create a top-level `assets` directory
- [ ] Move logos to the `assets` directory
  - [ ] Fix any broken links

**Comment by akankshasainics** [comment]
Hello! Can I work on this?

**Comment by paulosgf** [comment]
@akankshasainics , yes, you can!
Please pay special attention to links to README and the your documentation on GitHub.

**Comment by paulosgf** [comment]
I guess that it's in documentation too, in [https://pyhoneybot.github.io/honeybot/](https://pyhoneybot.github.io/honeybot/).
There you can search how to proceed to update the documentation itself.

**Comment by akankshasainics** [comment]
Thanks! I'll check it out.

**Comment by paulosgf** [comment]
> Thanks! I'll check it out.

👍🏿

**Comment by akankshasainics** [comment]
@paulosgf I have one question. As per the [documentation](https://pyhoneybot.github.io/honeybot/How_Tos/documentation.html), I have copied `gh-pages` branch to the `html` folder. There is a `_static` folder that contains some logos. Should I move those logos to also `assets` directory?

**Comment by paulosgf** [comment]
> @paulosgf I have one question. As per the [documentation](https://pyhoneybot.github.io/honeybot/How_Tos/documentation.html), I have copied `gh-pages` branch to the `html` folder. There is a `_static` folder that contains some logos. Should I move those logos to also `assets` directory? 

No. If you make, this'll create broken dependencies. But you should add these to your commit.
Don't forget to test in your fork first.

**Comment by akankshasainics** [comment]
Thanks!!
