### ISSUE TITLE
setup sphinx

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pyhoneybot/honeybot#13]
write appropriate comments in main.py and use sphinx to generate docs

**Comment by milliemcq** [comment]
I'll work on this 👍

**Comment by Abdur-rahmaanJ** [comment]
ok!

**Comment by Abdur-rahmaanJ** [comment]
please push new here https://github.com/pyhoneybot/pyhoneybot

**Comment by Macr0Nerd** [comment]
Sorry @milliemcq but due to time constraints this has been staked and claimed

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Zernerus** [comment]
I'll take over!
