### ISSUE TITLE
Convert lint styling from flake8 to black

### ISSUE THREAD

**Issue by paulosgf** [pyhoneybot/honeybot#137]
Convert lint styling from flake8 to black

**Comment by Abdur-rahmaanJ** [comment]
@MrTanoshii I prefer to completely ignore isortlint and stuffs

The proper way is to have a pyproject.toml coupled with pre-commit as seen [here](https://github.com/shopyo/shopyo)

@paulosgf if you can implement as is in the other project? Thanks (isort and black)

**Comment by paulosgf** [comment]
Sure! I was adapting the code base to the new lint style with black. Now I will be config the files. Later I'll make the pre-commit adjustment.
In time: do you want that I keep the bandit security checks @Abdur-rahmaanJ ?

**Comment by Abdur-rahmaanJ** [comment]
@Abdur-rahmaanJ Yes keep the Bandit check, for line, just let black's default handle that
