### ISSUE TITLE
create run.py file

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pyhoneybot/honeybot#14]
instead of if name equals main in main.py, create a new run.py file that imports from main.py and runs the bot

**Comment by ChristianSchneeweiss** [comment]
Hello I am a first timer and I would like to tackle this problem 😄 

Am I understanding it correctly that you want to have a run.py file which runs the code that is currently in the `if __name__ == '__main__'` in the main.py file?

**Comment by TomLisankie** [comment]
> Hello I am a first timer and I would like to tackle this problem 😄
> 
> Am I understanding it correctly that you want to have a run.py file which runs the code that is currently in the `if __name__ == '__main__'` in the main.py file?

Yes
