### ISSUE TITLE
New feature idea (IMDB)

### ISSUE THREAD

**Issue by ZoeyKats** [pyhoneybot/honeybot#184]
### Suggestion

Hello i am interested in implementing a new plugin that connects to the website https://www.imdb.com/
It will give information about a certain movie or series that the user asks for. Are you interested in me implementing it?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abdur-rahmaanJ** [comment]
@ZoeyKats Yes please!!!

**Comment by ZoeyKats** [comment]
Awesome i am already working on it! I have downloaded honeybot, is there any way you could help me a little on how to connect to the server from HexChat? I have created a new network with the right url, port and channel, but it keeps on giving me this error 

Connection failed ((336130315) error:1408F10B:SSL routines:ssl3_get_record:wrong version number)
 Are you sure this is a SSL capable server and port?

Thank you a lot!

**Comment by Abdur-rahmaanJ** [comment]
@ZoeyKats Well, for easy connections, choose the non-ssl version. See the README instructions ^^

**Comment by ZoeyKats** [comment]
Thank you a lot!

**Comment by paulosgf** [comment]
Done with #191
