### ISSUE TITLE
Feature Idea: Adding plugin with basketball info 

### ISSUE THREAD

**Issue by kefthymic** [pyhoneybot/honeybot#186]
### Suggestion

Hello. I am wondering if i could add a plugin that will show some information about Basketball World Cup and eurobasket. Through this plugin, someone can see which country won a specific year an event and also see how many medals has a country.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrTanoshii** [comment]
Merged in #187
