### ISSUE TITLE
Number of Stars and Fork plugin

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pyhoneybot/honeybot#20]
create a plugin to get the number of forks and stars for a given repo

```.repostats https://github.com/pyhoneybot/honeybot```

returns

```4 stars | 10 forks```

**Comment by shreyanshrs44** [comment]
Hi, I would like to work one this issue !

**Comment by Abdur-rahmaanJ** [comment]
@shreyanshrs44 go ahead!

**Comment by shreyanshrs44** [comment]
Thanks ! I have wrote Python script using GraphQL Api to get number of forks and stars for this repo `https://github.com/pyhoneybot/honeybot`. How I should go about making it as plugin and fix the issue ?

**Comment by Abdur-rahmaanJ** [comment]
@shreyanshrs44 tried running the bot?

**Comment by shreyanshrs44** [comment]
Yes. I tried building docker image and it ran without errors. But while running docker image it shows nothing. (Maybe I am missing somehing)
To build :- `sudo docker build -t honeybot -f ./docker/Dockerfile `
To run :-  `sudo docker run honeybot`

**Comment by Abdur-rahmaanJ** [comment]
@shreyanshrs44 i mean run ```python run.py```

**Comment by shreyanshrs44** [comment]
Thanks I will try to do the same and try to create plugin in the format mentioned in the readme.

**Comment by Abdur-rahmaanJ** [comment]
@shreyanshrs44 see a simple plugin, copy and modify

**Comment by shreyanshrs44** [comment]
I am accessing github api hence I am using my personal access token. So what should I do before sending pull request?

**Comment by Abdur-rahmaanJ** [comment]
@shreyanshrs44 no just a simple serving of beaitiful soup, no need for auth etc

**Comment by shreyanshrs44** [comment]
okay. Actually I wrote using github api. Now I will look about using BS. Thanks for help !

**Comment by shreyanshrs44** [comment]
Yes, Using BS will be very much easy !

**Comment by mallepallihimasagar** [comment]
I want to work on this:)

**Comment by Abdur-rahmaanJ** [comment]
@mallepallihimasagar ah sorry been solved by PR #24 but, we'll launch new issues soon!
