### ISSUE TITLE
Feature Idea: Adding plugin with top anime info

### ISSUE THREAD

**Issue by cdkontos** [pyhoneybot/honeybot#203]
### Suggestion

Hello.

I was wondering if i could add a plugin that will show information about the top 100 anime and some information about them like their score. Through this plugin, someone can see what their score is on the myanimelist site as well as release date and ranking.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abdur-rahmaanJ** [comment]
@cdkontos Hi you know Python? If so, we can help you create the plugin!

**Comment by cdkontos** [comment]
@Abdur-rahmaanJ yes hello i have already made the plugin in a fork i made of the project

**Comment by Abdur-rahmaanJ** [comment]
@cdkontos We would be very grateful if you could PR it back!

**Comment by cdkontos** [comment]
@Abdur-rahmaanJ did it now

**Comment by Abdur-rahmaanJ** [comment]
@cdkontos Thank you!
