### ISSUE TITLE
book of the day plugin

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pyhoneybot/honeybot#21]
using [bookoftheday.org](https://bookoftheday.org), get the title and link of the book of the day

```.bookoftheday```

returns

```https://bookoftheday.org/fleishman-is-in-trouble-taffy-brodesser-akner/```

**Comment by stschoberg** [comment]
Hey I'd love to take this if nobody has yet!

**Comment by Abdur-rahmaanJ** [comment]
@stschoberg yes, sure!

**Comment by GideonStevens** [comment]
I run bookoftheday.org, how can I help? "Today's Book" always posts at 12:05 New York City time. If you grab the RSS feed after that, the first one is the book of the day.
