### ISSUE TITLE
Search Pypi Plugin

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pyhoneybot/honeybot#26]
sending ```.pypi flask```

returns the first 3 links in 3 messages

```
https://...
https://...
https://...
```

**Comment by de-Blaxe** [comment]
Could I work on this?

**Comment by Abdur-rahmaanJ** [comment]
@de-Blaxe yeps!

**Comment by Macr0Nerd** [comment]
@de-Blaxe what is the status of this issue?

**Comment by de-Blaxe** [comment]
@Macr0Nerd Sorry I got caught up in something, it should be done today or tomorrow.

**Comment by Macr0Nerd** [comment]
Resolved.
