### ISSUE TITLE
Change docstrings to sphinx-supported syntax

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pyhoneybot/honeybot#27]
In main.py, change dosctrings to sphinx rst syntax, currently they are by hands!

**Comment by ec10K** [comment]
Hi @Abdur-rahmaanJ , it's my first time working on an open source project. Can you specify which changes you want made inside main.py. I've forked the repo and am looking into it. Thanks.

**Comment by Abdur-rahmaanJ** [comment]
@ec10K see how sphinx needs docstrings. change the existing docstring to that!

**Comment by lOne9wOlf** [comment]
is this still open

**Comment by Zernerus** [comment]
@lOne9wOlf The Docstrings are already in sphinx rst syntax, (Google format with napoleon).
What you could do is finish the docstrings by describing the functions, classes and methods, etc. in main.py since they are partially incomplete.
