### ISSUE TITLE
Complete docstrings in main.py

### ISSUE THREAD

**Issue by Zernerus** [pyhoneybot/honeybot#39]
Currently there are incomplete or example docstrings in **main.py** in Google style, see [here](http://google.github.io/styleguide/pyguide.html).

The task would be to **understand the code** in main.py and **document it properly**, following our guide [here](https://github.com/pyhoneybot/honeybot). This will require some time since you'll need to understand the code but it is (in my opinion) a good introductory to the project. 

If you have **any** questions or problems regarding the task or the documentation guide let me know or ask on our discord!

**Comment by RenatoViana01** [comment]
Can I pick this up?

**Comment by Abdur-rahmaanJ** [comment]
`yes`

**Comment by h-ranjan1110** [comment]
@RenatoViana01 are you still working on this ?

**Comment by RenatoViana01** [comment]
slowly but yea

**Comment by EinKaiser** [comment]
Hey can I work on this?

**Comment by Macr0Nerd** [comment]
>Hey can I work on this?

@EinKaiser feel free

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cosky5** [comment]
I'm very new and would like to do this as my first start, can I?

**Comment by kevintham** [comment]
Is anybody still working on this? I would like to get assigned to this issue if possible!

**Comment by Macr0Nerd** [comment]
>Is anybody still working on this? I would like to get assigned to this issue if possible!

@kevintham go ahead

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lishing** [comment]
can i pick this up?

**Comment by Macr0Nerd** [comment]
>can i pick this up?

@lishing as the last reply was a month ago, please do

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Guddu327** [comment]
Hey, I am new to open-source. Can I work on this..?

**Comment by Abhijnan-Bajpai** [comment]
I am looking for a first pull request opportunity on GitHub. Is this thread still open? I would love to contribute.

**Comment by Abdur-rahmaanJ** [comment]
@Abhijnan-Bajpai no. Maybe a plugin would make a nicer contribution?
