### ISSUE TITLE
Add string formatting in main.py

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pyhoneybot/honeybot#43]
use .format with strings like this: ```"PRIVMSG " + target + " :" + msg + "\r\n"```

**Comment by Boltbase** [comment]
Mind if I give it a shot?

**Comment by Zigelzi** [comment]
Is there particular reason to use .format instead of f-strings?

**Comment by Abdur-rahmaanJ** [comment]
@Zigelzi nope
