### ISSUE TITLE
Change return in main.py

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pyhoneybot/honeybot#44]
change return [here](https://github.com/pyhoneybot/honeybot/blob/master/honeybot/main.py#L238) to

```
return '' if x is None else x
```

**Comment by bukandu1** [comment]
I don’t mind making this change.

**Comment by Abdur-rahmaanJ** [comment]
@bukandu1 ok assigning you!

**Comment by sau2019** [comment]
if x is None
return 0
else
return x

try this out

**Comment by Macr0Nerd** [comment]
Resolved
