### ISSUE TITLE
Random Colour plugin description

### ISSUE THREAD

**Issue by amanzholov8** [pyhoneybot/honeybot#50]
In the README.md file I saw "Random Color" under "To-do plugins". I think I can make this plugin, but I wanted to get a more detailed description of what this plugin needs to do if possible.

**Comment by Macr0Nerd** [comment]
Hi @amanzholov8 sorry for the late response. It looks like there isn't too much put down as for info, so I'd say that you can just return a random colour when prompted (by something like `.rancol`) and use the [IRC colour codes](https://www.mirc.com/colors.html) to also show that colour. Should be simple enough.

If you want to get really fancy with it, then you can dig up some obscure colours from who knows where, but it isn't necessary! Those 16 (or is it 12?) colours should be more than enough. Have fun!

**Comment by spassaro80** [comment]
¿Hello, can i pìck it up? First Timer contributor.

**Comment by GlennToms** [comment]
@spassaro80 Doesn't look like this is being worked on.  Please take it if you still want it

**Comment by Genza999** [comment]
@spassaro80 are you working on this? If not, I'd like to pick this up.

**Comment by spassaro80** [comment]
> @spassaro80 are you working on this? If not, I'd like to pick this up.

ok, go ahead.

**Comment by EinKaiser** [comment]
Hi, is this issue still open?
