### ISSUE TITLE
Contribute to documentation broken link at Readme

### ISSUE THREAD

**Issue by Gonmeso** [pyhoneybot/honeybot#61]
Hello,

At the contributing section regarding documentation the current link is broken, redirecting to a non existing [page](https://pyhoneybot.github.io/honeybot/documentation.html).

I've been looking around and I've seen that the new page might be [this one](https://pyhoneybot.github.io/honeybot/How_Tos/contributing.html#updating-the-docs). But I've notice that most of what is explained in the read the docs is currently at `Readme`. So I could be a good idea to add the documentation info at `Readme` or fix the link.

If this is considered an Issue I could make a PR 😃

**Comment by AngeloGiacco** [comment]
sure @Gonmeso 

maybe the PR could also make sure all plugins are included in the documentation

**Comment by ria-19** [comment]
Is this issue open, I would like to contribute if it.

**Comment by AngeloGiacco** [comment]
Sure go for it

**Comment by ria-19** [comment]
Thank you!

**Comment by ria-19** [comment]
I have updated both the broken links in the docs. The discord links are still broken though.
