### ISSUE TITLE
telephone code plugin

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pyhoneybot/honeybot#63]
.tel mu

returns

+230

where mu is the shorthand code of mauritius

**Comment by dubesar** [comment]
@Abdur-rahmaanJ  what has to be done exactly for this?

**Comment by Abdur-rahmaanJ** [comment]
@dubesar see the plugins folder, see a plugin how it works etc then implement a plugin than when given country code in letters it returns the international telephone prefix

**Comment by dubesar** [comment]
@Abdur-rahmaanJ  I would like to work on it
