### ISSUE TITLE
Random Trailer Park Boys quote

### ISSUE THREAD

**Issue by wupewu** [pyhoneybot/honeybot#8]
Good source of quotes:
* https://en.wikiquote.org/wiki/Trailer_Park_Boys
Ideas:
* Use BeautifulSoup to parse quotes from wikiquote

**Comment by msarfrazanwar** [comment]
I will work on this. Can you give specific instructions of what is required?

**Comment by Divyanshu29** [comment]
May i also contribute to solving this issue?

**Comment by wupewu** [comment]
Example:
* https://github.com/pyhoneybot/honeybot/blob/master/honeybot/plugins/joke.py

**Comment by wupewu** [comment]
Possible improvements:
* crawling quotes from wikiquote

**Comment by Divyanshu29** [comment]
Okay I am doing it and have started it :)
