### ISSUE TITLE
Docstring to info.py - coin_toss

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pyhoneybot/honeybot#82]
Just like [this docstring](https://github.com/pyhoneybot/honeybot/blob/4992519c6236448a9d767d93ee1f16e305dbb6c4/honeybot/plugins/downloaded/abbreviation/main.py#L2) 
was turned into [info.py](https://github.com/pyhoneybot/honeybot/blob/master/honeybot/plugins/downloaded/abbreviation/info.py#L1) 
file, do so for the 
[coin_toss](https://github.com/pyhoneybot/honeybot/tree/master/honeybot/plugins/downloaded/coin_toss) folder

**Comment by SamuelJohnson01997** [comment]
Hi. I'd like to take this up.

**Comment by Macr0Nerd** [comment]
@SamuelJohnson01997 feel free to!

**Comment by SamuelJohnson01997** [comment]
Hi. It's already in the expected format I think so. Kindly check and let me know what to be changed if I'm missing anything. Thank you.. 
docstring - https://github.com/pyhoneybot/honeybot/blob/master/honeybot/plugins/downloaded/cointoss/main.py
info.py - https://github.com/pyhoneybot/honeybot/blob/master/honeybot/plugins/downloaded/cointoss/info.py

**Comment by Abdur-rahmaanJ** [comment]
@SamuelJohnson01997 Ah awefully sorry feel free to do it for caesar_cipher issue #80
