### ISSUE TITLE
Add more facts to the facts plugin

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pyhoneybot/honeybot#87]
See plugins the [fact plugin](https://github.com/pyhoneybot/honeybot/blob/master/honeybot/plugins/downloaded/fact/main.py) Add as many facts as you can!

**Comment by ria-19** [comment]
I am a beginner in the open-source world, can I work on this?

**Comment by Abdur-rahmaanJ** [comment]
@ria-19 yes for sure. Anything just ping!

**Comment by ria-19** [comment]
Thank you! I have created a pull request.
